# Generated by Django 5.2.7 on 2025-10-30 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo de Artículo',
                'verbose_name_plural': 'Grupos de Artículos',
                'db_table': 'grupo_articulo',
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Línea de Artículo',
                'verbose_name_plural': 'Líneas de Artículos',
                'db_table': 'linea_articulo',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='UND', max_length=20)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='core.grupoarticulo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
            },
        ),
        migrations.AddField(
            model_name='grupoarticulo',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.lineaarticulo'),
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('ESPECIAL', 'Especial')], default='GENERAL', max_length=20)),
                ('canal', models.CharField(choices=[('TODOS', 'Todos'), ('TIENDA', 'Tienda Física'), ('ONLINE', 'Online'), ('DISTRIBUIDOR', 'Distribuidor'), ('CORPORATIVO', 'Corporativo')], default='TODOS', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'lista_precio',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_minima', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], default='PORCENTAJE', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('articulos', models.ManyToManyField(blank=True, related_name='combinaciones', to='core.articulo')),
                ('grupo_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grupoarticulo')),
                ('linea_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lineaarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='core.listaprecio')),
            ],
            options={
                'verbose_name': 'Combinación de Producto',
                'verbose_name_plural': 'Combinaciones de Productos',
                'db_table': 'combinacion_producto',
            },
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_regla', models.CharField(choices=[('CANAL', 'Por Canal de Venta'), ('ESCALA_UNIDADES', 'Por Escala de Unidades'), ('ESCALA_MONTO', 'Por Escala de Monto'), ('MONTO_PEDIDO', 'Por Monto Total del Pedido'), ('COMBINACION', 'Por Combinación de Productos')], max_length=20)),
                ('tipo_ajuste', models.CharField(choices=[('PORCENTAJE', 'Porcentaje de Descuento'), ('MONTO_FIJO', 'Monto Fijo de Descuento'), ('PRECIO_FIJO', 'Precio Fijo')], default='PORCENTAJE', max_length=20)),
                ('cantidad_minima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_maxima', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_ajuste', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('prioridad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_precio', to='core.grupoarticulo')),
                ('linea_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_precio', to='core.lineaarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='core.listaprecio')),
            ],
            options={
                'verbose_name': 'Regla de Precio',
                'verbose_name_plural': 'Reglas de Precios',
                'db_table': 'regla_precio',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reglas_aplicadas', models.TextField(blank=True)),
                ('bajo_costo', models.BooleanField(default=False)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listaprecio')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
                'db_table': 'detalle_orden_compra_cliente',
            },
        ),
        migrations.CreateModel(
            name='PrecioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bajo_costo', models.BooleanField(default=False)),
                ('descuento_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('autorizado_por', models.CharField(blank=True, max_length=200)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.articulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.listaprecio')),
            ],
            options={
                'verbose_name': 'Precio de Artículo',
                'verbose_name_plural': 'Precios de Artículos',
                'db_table': 'precio_articulo',
                'unique_together': {('lista_precio', 'articulo')},
            },
        ),
    ]
